### ISSUE TITLE
Cannot use FTP or SFTP as dir.uri

### ISSUE THREAD

**Issue by dilini-muthumala** [siddhi-io/siddhi-io-file#122]
**Description:**
Following error observed when an FTP URL is specified as the dir.uri

```
Error on 'SiddhiApp3'. Connection to the file directory is lost. Error while connecting at Source 'file' at 'SweetProductionStream'. Will retry in '15 sec'. io.siddhi.core.exception.ConnectionUnavailableException: Connection to the file directory is lost.
at io.siddhi.extension.io.file.FileSource.deployServers(FileSource.java:787)
at io.siddhi.extension.io.file.FileSource.connect(FileSource.java:572)
at io.siddhi.extension.io.file.FileSource.connect(FileSource.java:83)
at io.siddhi.core.stream.input.source.Source.connectWithRetry(Source.java:160)
at io.siddhi.core.stream.input.source.Source$1.run(Source.java:185)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.transport.remotefilesystem.exception.RemoteFileSystemConnectorException: Failed to initialize File server connector for Service: SiddhiApp3
at org.wso2.transport.remotefilesystem.server.connector.contractimpl.RemoteFileSystemServerConnectorImpl.<init>(RemoteFileSystemServerConnectorImpl.java:46)
at org.wso2.transport.remotefilesystem.impl.RemoteFileSystemConnectorFactoryImpl.createServerConnector(RemoteFileSystemConnectorFactoryImpl.java:40)
at io.siddhi.extension.io.file.FileSource.deployServers(FileSource.java:768)
... 11 more
Caused by: org.wso2.transport.remotefilesystem.exception.RemoteFileSystemConnectorException: [SiddhiApp3] File system server connector is used to listen to a folder. But the given path does not refer to a folder.
at org.wso2.transport.remotefilesystem.server.RemoteFileSystemConsumer.<init>(RemoteFileSystemConsumer.java:80)
at org.wso2.transport.remotefilesystem.server.connector.contractimpl.RemoteFileSystemServerConnectorImpl.<init>(RemoteFileSystemServerConnectorImpl.java:44)
... 13 more
```
**Affected Product Version:**
SI 1.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Use following siddhi app to reproduce:
```
@App:name("SiddhiApp3")

@App:description("Description of the plan")

@source(type='file', mode='line',
dir.uri='ftp://bob:12345@localhost:21/wrthgy',
file.system.options='PASSIVE_MODE:true',
action.after.process='keep',
tailing='false',
@map(type='csv'))
define stream SweetProductionStream (name string, amount long);

@sink(type='log')
define stream OutputStream (name string, amount long);

from SweetProductionStream
select *
insert into OutputStream;
```

**Comment by dilini-muthumala** [comment]
Fixed by @ramindu90 with the following commits:

https://github.com/wso2/transport-file/commit/b88a62fa631999abcc7892e01d74b4d641f0c1c4
https://github.com/wso2/transport-file/commit/3a24c99f9b48594ab0c2fbc48586389021a9e168
https://github.com/wso2/transport-file/commit/264e635ca3af18750e6fa3bdcd3f3658fc79529c

https://github.com/siddhi-io/siddhi-io-file/commit/0355d041748feb7f4c7bd2a76a8e6db985093abd
https://github.com/siddhi-io/siddhi-io-file/commit/4858827171969d749751e3f580fa6dee853c83a8
