### ISSUE TITLE
Reading large file overflow the heap space: OutofMemoryError

### ISSUE THREAD

**Issue by samhuss** [siddhi-io/siddhi-io-file#59]
**Description:**
I'm trying to read a database dump file more than 1GB to build a database and use it in Elasticsearch after cleaning and transforming the data (ETL). Before running siddhi app, I increased the memory to 4GB for both the editor and the worker in case the worker is executed by the editor. 

After checking the source code of the remote file transporter, it seems like this method "VFSClientConnector.toByteArray" keeps reading the file to the end and acquiring more buffer with no limits or without waiting till read buffer to be flushed first which breaks the heap size. 

Please advise if there is any other extension that reads large files without breaking the memory.

I'm currently using Logstash to overcome these issues, however I'm wishing to use siddhi in production but unfortunately I can't use it at the moment with this issue.

The exception thrown is:
Exception in thread "remote-file-1-thread-1" java.lang.OutOfMemoryError: Java heap space                                                                                                                     
        at java.util.Arrays.copyOf(Arrays.java:3236)                                                                                                                                                         
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)                                                                                                                                
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)                                                                                                                       
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)                                                                                                                               
        at org.wso2.transport.file.connector.sender.VFSClientConnector.toByteArray(VFSClientConnector.java:221)                                           
        at org.wso2.transport.file.connector.sender.VFSClientConnector.send(VFSClientConnector.java:172)                                                               
        at org.wso2.extension.siddhi.io.file.listeners.FileSystemListener.onMessage(FileSystemListener.java:173)                                     
        at org.wso2.transport.remotefilesystem.server.RemoteFileSystemProcessor.run(RemoteFileSystemProcessor.java:89)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Code that throws the exception here:
at org.wso2.transport.file.connector.sender.VFSClientConnector.send(VFSClientConnector.java:172) 

https://www.programcreek.com/java-api-examples/?code=wso2%2Fcarbon-transports%2Fcarbon-transports-master%2Ffile%2Forg.wso2.carbon.transport.remote-file-system%2Fsrc%2Fmain%2Fjava%2Forg%2Fwso2%2Fcarbon%2Ftransport%2Fremotefilesystem%2Fserver%2FRemoteFileSystemProcessor.java#

/**
     * Obtain a byte[] from an input stream
     *
     * @param input The input stream that the data should be obtained from
     * @return byte[] The byte array of data obtained from the input stream
     * @throws IOException
     */
    private static byte[] toByteArray(InputStream input) throws IOException {
        long count = 0L;
        byte[] buffer = new byte[4096];
        int n1;
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        for (; -1 != (n1 = input.read(buffer)); count += (long) n1) {
            output.write(buffer, 0, n1);
        }
        if (logger.isDebugEnabled()) {
            logger.debug(count + " bytes read");
        }
        byte[] bytes = output.toByteArray();
        closeQuietly(output);
        return bytes;
    }

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ramindu90** [comment]
This is fixed with https://github.com/wso2/transport-file/commit/6a748afde5d1135cc27e078c8a1d1ff2557bf293.
Please use the latest extension version (v2.0.3)
